/****
 Função: Lista os PS abertos (dentro do período de inscrição) para o candidato iniciar a inscrição.
 ****/
DECLARE @PIDPS VARCHAR(10);

SET @PIDPS = :IDPS;

SELECT
    SPSPROCESSOSELETIVO.CODFILIAL AS CODUNIDADE,
    SPSPROCESSOSELETIVO.NOME,
    FILIAL.NOME AS NOMEUNIDADE,
    CONCAT(SPSPROCESSOSELETIVO.CODCOLIGADA,'-',SPSPROCESSOSELETIVO.IDPS) AS CODEXTERNO
FROM SPSPROCESSOSELETIVO (NOLOCK)
OUTER APPLY(
    SELECT
        NOME,
        CODFILIAL
    FROM GFILIAL (NOLOCK)
    WHERE GFILIAL.CODCOLIGADA = SPSPROCESSOSELETIVO.CODCOLIGADA
        AND GFILIAL.CODFILIAL = SPSPROCESSOSELETIVO.CODFILIAL
) AS FILIAL

WHERE SPSPROCESSOSELETIVO.STATUS = 'T'
    AND (SPSPROCESSOSELETIVO.IDPS = @PIDPS OR @PIDPS = '')
    AND GETDATE() BETWEEN SPSPROCESSOSELETIVO.DTINIINSCRICAO AND SPSPROCESSOSELETIVO.DTFIMINSCRICAO

ORDER BY SPSPROCESSOSELETIVO.NOME
